sudo: false
language: python
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
branches:
  except:
    - /^WIP-.*$/
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install -U pip
  - pip install pyflakes coverage codecov
  - pip install --editable .
script:
  - pyflakes setup.py src
  - wormhole --version
  - coverage run --branch `which trial` wormhole
after_success:
  - coverage report
  - codecov
